server:
    port: 8778

spring:
    datasource:
        url: jdbc:mysql://14.215.116.215:3306/zshjq_jwb?useUnicode=true&characterEncoding=utf8
        username: zshj
        password: zshjjrb
        driver-class-name: com.mysql.jdbc.Driver

    application:
        name: esgov-jrw-sysmgrservice
    cloud:
        zookeeper:
            connect-string: 10.142.233.80:8181
            discovery:
                register: true
                instance-host: ${KETTY_IP}
                instance-port: ${server.port}
                instance-id: ${spring.cloud.zookeeper.discovery.instance-host}:${spring.cloud.zookeeper.discovery.instance-port}

mybatis-plus:
    mapper-locations: classpath:/dao/*Dao.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.esgov.jrw.sysmgrservice.entity.*
    #通用枚举
    typeEnumsPackage: com.esgov.jrw.sysmgrservice.entity.enums
    global-config:
        id-type: 3
        #逻辑删除配置
        logic-delete-value: 0
        logic-not-delete-value: 1
#        sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
        # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
        sql-parser-cache: true
        #热更新 改动xml不用重启
        refresh-mapper: true
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
jasypt:
  encryptor:
    password: esgov
swagger:
    basePackage: com.esgov.jrw.jrwservice.controller
    title: esgov-jrw-sysmgrservice RESTful APIs
    description: esgov-jrw-sysmgrservice RESTful API 文档
    version: 1.0.0-SNAPSHOT
